language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ShortDocumentation' ]; then cd .. && eval "mv $currentfolder ShortDocumentation" && cd ShortDocumentation; fi

